apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
    - namespace.yaml
    - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.8/manifests/install.yaml

patchesStrategicMerge:
    - argocd-server-service.yaml