apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
    - namespace.yaml
    - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.8/manifests/install.yaml
    - application-argocd.yaml
    - application-echo.yaml

patches:
    - target:
        kind: Service
        name: argocd-server
      path: argocd-server-service.yaml
      